// const attributes = [
//   {
//     ID: 1,
//     NAME: "Color",
//     "DISPLAY NAME": "Color",
//     PUBLISHED: true,
//     VALUES: "Teal",
//     ACTION: "Delete",
//   },
//   {
//     ID: 2,
//     NAME: "Color",
//     "DISPLAY NAME": "Color",
//     PUBLISHED: false,
//     VALUES: "Khaki",
//     ACTION: "Edit",
//   },
//   {
//     ID: 3,
//     NAME: "Color",
//     "DISPLAY NAME": "Color",
//     PUBLISHED: true,
//     VALUES: "Orange",
//     ACTION: "Delete",
//   },
//   {
//     ID: 4,
//     NAME: "Color",
//     "DISPLAY NAME": "Color",
//     PUBLISHED: true,
//     VALUES: "Green",
//     ACTION: "Delete",
//   },
//   {
//     ID: 5,
//     NAME: "Color",
//     "DISPLAY NAME": "Color",
//     PUBLISHED: false,
//     VALUES: "Green",
//     ACTION: "Delete",
//   },
//   {
//     ID: 6,
//     NAME: "Color",
//     "DISPLAY NAME": "Color",
//     PUBLISHED: true,
//     VALUES: "Mauv",
//     ACTION: "Delete",
//   },
//   {
//     ID: 7,
//     NAME: "Color",
//     "DISPLAY NAME": "Color",
//     PUBLISHED: false,
//     VALUES: "Violet",
//     ACTION: "Edit",
//   },
//   {
//     ID: 8,
//     NAME: "Color",
//     "DISPLAY NAME": "Color",
//     PUBLISHED: true,
//     VALUES: "Blue",
//     ACTION: "Edit",
//   },
//   {
//     ID: 9,
//     NAME: "Color",
//     "DISPLAY NAME": "Color",
//     PUBLISHED: true,
//     VALUES: "Maroon",
//     ACTION: "Delete",
//   },
//   {
//     ID: 10,
//     NAME: "Color",
//     "DISPLAY NAME": "Color",
//     PUBLISHED: true,
//     VALUES: "Turquoise",
//     ACTION: "Delete",
//   },
// ];

const attributes = [
  {
    ID: 1,
    NAME: "Color",
    "DISPLAY NAME": "Color",
    PUBLISHED: true,
    VALUES: [
      {
        ID: 1,
        "DISPLAY NAME": "Teal",
        VALUE: "Teal",
        PUBLISHED: true,
        ACTION: "Edit",
      },
      {
        ID: 2,
        "DISPLAY NAME": "Khaki",
        VALUE: "Khaki",
        PUBLISHED: true,
        ACTION: "Delete",
      },
      {
        ID: 3,
        "DISPLAY NAME": "Orange",
        VALUE: "Orange",
        PUBLISHED: true,
        ACTION: "Delete",
      },
      {
        ID: 4,
        "DISPLAY NAME": "Green",
        VALUE: "Green",
        PUBLISHED: true,
        ACTION: "Delete",
      },
      {
        ID: 5,
        "DISPLAY NAME": "Mauv",
        VALUE: "Mauv",
        PUBLISHED: true,
        ACTION: "Delete",
      },
    ],

    ACTION: "Delete",
  },
  {
    ID: 2,
    NAME: "Size",
    "DISPLAY NAME": "Size",
    PUBLISHED: true,
    VALUES: [
      {
        ID: 1,
        "DISPLAY NAME": "Small",
        VALUE: "Small",
        PUBLISHED: true,
        ACTION: "Edit",
      },
      {
        ID: 2,
        "DISPLAY NAME": "Large",
        VALUE: "Large",
        PUBLISHED: true,
        ACTION: "Edit",
      },
    ],
    ACTION: "Delete",
  },
  {
    ID: 3,
    NAME: "Material",
    "DISPLAY NAME": "Material",
    PUBLISHED: true,
    VALUES: [
      {
        ID: 1,
        "DISPLAY NAME": "Leather",
        VALUE: "Leather",
        PUBLISHED: true,
        ACTION: "Edit",
      },
      {
        ID: 2,
        "DISPLAY NAME": "Cotton",
        VALUE: "Cotton",
        PUBLISHED: true,
        ACTION: "Edit",
      },
    ],
    ACTION: "Delete",
  },
];

export { attributes };
