const categories = [
  {
    ID: "37-926-5044",
    Icon: "2XL",
    Name: "Automotive",
    Description: "Home",
    PUBLISHED: true,
    ACTIONS: "Search",
  },
  {
    ID: "79-451-5956",
    Icon: "XL",
    Name: "Automotive",
    Description: "Shoes",
    PUBLISHED: true,
    ACTIONS: "Edit",
  },
  {
    ID: "47-774-0891",
    Icon: "XL",
    Name: "Jewelry",
    Description: "Sports",
    PUBLISHED: true,
    ACTIONS: "Delete",
  },
  {
    ID: "74-824-2179",
    Icon: "2XL",
    Name: "Home",
    Description: "Health",
    PUBLISHED: false,
    ACTIONS: "Edit",
  },
  {
    ID: "43-022-6869",
    Icon: "2XL",
    Name: "Automotive",
    Description: "Sports",
    PUBLISHED: true,
    ACTIONS: "Search",
  },
  {
    ID: "81-641-0353",
    Icon: "XS",
    Name: "Health",
    Description: "Music",
    PUBLISHED: true,
    ACTIONS: "Edit",
  },
  {
    ID: "60-216-7387",
    Icon: "L",
    Name: "Home",
    Description: "Garden",
    PUBLISHED: false,
    ACTIONS: "Delete",
  },
  {
    ID: "28-913-3760",
    Icon: "L",
    Name: "Books",
    Description: "Baby",
    PUBLISHED: true,
    ACTIONS: "Search",
  },
  {
    ID: "89-343-6571",
    Icon: "XS",
    Name: "Automotive",
    Description: "Beauty",
    PUBLISHED: true,
    ACTIONS: "Search",
  },
  {
    ID: "56-210-9680",
    Icon: "M",
    Name: "Kids",
    Description: "Garden",
    PUBLISHED: true,
    ACTIONS: "Delete",
  },
  {
    ID: "71-856-6367",
    Icon: "XS",
    Name: "Shoes",
    Description: "Beauty",
    PUBLISHED: true,
    ACTIONS: "Delete",
  },
  {
    ID: "78-442-6090",
    Icon: "S",
    Name: "Toys",
    Description: "Toys",
    PUBLISHED: true,
    ACTIONS: "Delete",
  },
  {
    ID: "13-887-9947",
    Icon: "L",
    Name: "Toys",
    Description: "Music",
    PUBLISHED: true,
    ACTIONS: "Delete",
  },
  {
    ID: "05-223-6069",
    Icon: "3XL",
    Name: "Clothing",
    Description: "Industrial",
    PUBLISHED: true,
    ACTIONS: "Delete",
  },
  {
    ID: "66-855-9530",
    Icon: "S",
    Name: "Automotive",
    Description: "Beauty",
    PUBLISHED: false,
    ACTIONS: "Delete",
  },
  {
    ID: "52-293-6479",
    Icon: "3XL",
    Name: "Books",
    Description: "Automotive",
    PUBLISHED: false,
    ACTIONS: "Search",
  },
  {
    ID: "98-584-7938",
    Icon: "S",
    Name: "Shoes",
    Description: "Garden",
    PUBLISHED: true,
    ACTIONS: "Edit",
  },
  {
    ID: "72-764-1062",
    Icon: "XS",
    Name: "Outdoors",
    Description: "Shoes",
    PUBLISHED: false,
    ACTIONS: "Delete",
  },
  {
    ID: "59-884-1849",
    Icon: "2XL",
    Name: "Music",
    Description: "Industrial",
    PUBLISHED: false,
    ACTIONS: "Delete",
  },
  {
    ID: "11-133-4886",
    Icon: "L",
    Name: "Grocery",
    Description: "Shoes",
    PUBLISHED: false,
    ACTIONS: "Delete",
  },
  {
    ID: "98-733-2674",
    Icon: "3XL",
    Name: "Computers",
    Description: "Automotive",
    PUBLISHED: false,
    ACTIONS: "Delete",
  },
  {
    ID: "90-631-7638",
    Icon: "L",
    Name: "Movies",
    Description: "Tools",
    PUBLISHED: false,
    ACTIONS: "Edit",
  },
  {
    ID: "67-282-1552",
    Icon: "3XL",
    Name: "Shoes",
    Description: "Home",
    PUBLISHED: true,
    ACTIONS: "Delete",
  },
  {
    ID: "75-414-3395",
    Icon: "XS",
    Name: "Kids",
    Description: "Beauty",
    PUBLISHED: false,
    ACTIONS: "Edit",
  },
  {
    ID: "78-168-6991",
    Icon: "S",
    Name: "Industrial",
    Description: "Computers",
    PUBLISHED: false,
    ACTIONS: "Edit",
  },
  {
    ID: "71-623-5614",
    Icon: "M",
    Name: "Tools",
    Description: "Electronics",
    PUBLISHED: false,
    ACTIONS: "Edit",
  },
  {
    ID: "14-765-1593",
    Icon: "2XL",
    Name: "Garden",
    Description: "Tools",
    PUBLISHED: true,
    ACTIONS: "Edit",
  },
  {
    ID: "42-219-1041",
    Icon: "S",
    Name: "Games",
    Description: "Automotive",
    PUBLISHED: false,
    ACTIONS: "Edit",
  },
  {
    ID: "38-445-5532",
    Icon: "XS",
    Name: "Health",
    Description: "Beauty",
    PUBLISHED: true,
    ACTIONS: "Edit",
  },
  {
    ID: "17-897-7483",
    Icon: "M",
    Name: "Baby",
    Description: "Toys",
    PUBLISHED: true,
    ACTIONS: "Edit",
  },
  {
    ID: "74-035-0829",
    Icon: "2XL",
    Name: "Computers",
    Description: "Grocery",
    PUBLISHED: true,
    ACTIONS: "Delete",
  },
  {
    ID: "45-920-0596",
    Icon: "2XL",
    Name: "Games",
    Description: "Beauty",
    PUBLISHED: true,
    ACTIONS: "Edit",
  },
  {
    ID: "79-552-1365",
    Icon: "2XL",
    Name: "Tools",
    Description: "Baby",
    PUBLISHED: false,
    ACTIONS: "Delete",
  },
  {
    ID: "89-464-6292",
    Icon: "3XL",
    Name: "Shoes",
    Description: "Clothing",
    PUBLISHED: false,
    ACTIONS: "Delete",
  },
  {
    ID: "36-725-0139",
    Icon: "3XL",
    Name: "Beauty",
    Description: "Games",
    PUBLISHED: false,
    ACTIONS: "Edit",
  },
  {
    ID: "12-763-2552",
    Icon: "S",
    Name: "Movies",
    Description: "Clothing",
    PUBLISHED: true,
    ACTIONS: "Search",
  },
  {
    ID: "90-739-2634",
    Icon: "2XL",
    Name: "Jewelry",
    Description: "Industrial",
    PUBLISHED: false,
    ACTIONS: "Search",
  },
  {
    ID: "03-576-6098",
    Icon: "2XL",
    Name: "Games",
    Description: "Games",
    PUBLISHED: true,
    ACTIONS: "Edit",
  },
  {
    ID: "48-566-4672",
    Icon: "XL",
    Name: "Clothing",
    Description: "Electronics",
    PUBLISHED: true,
    ACTIONS: "Edit",
  },
  {
    ID: "34-305-2715",
    Icon: "L",
    Name: "Electronics",
    Description: "Tools",
    PUBLISHED: false,
    ACTIONS: "Delete",
  },
  {
    ID: "37-927-8664",
    Icon: "L",
    Name: "Books",
    Description: "Industrial",
    PUBLISHED: false,
    ACTIONS: "Edit",
  },
  {
    ID: "91-907-3201",
    Icon: "M",
    Name: "Garden",
    Description: "Music",
    PUBLISHED: false,
    ACTIONS: "Delete",
  },
  {
    ID: "35-268-5569",
    Icon: "2XL",
    Name: "Movies",
    Description: "Industrial",
    PUBLISHED: false,
    ACTIONS: "Edit",
  },
  {
    ID: "76-667-8299",
    Icon: "M",
    Name: "Music",
    Description: "Clothing",
    PUBLISHED: false,
    ACTIONS: "Edit",
  },
  {
    ID: "31-980-6691",
    Icon: "2XL",
    Name: "Health",
    Description: "Beauty",
    PUBLISHED: true,
    ACTIONS: "Delete",
  },
  {
    ID: "78-472-6190",
    Icon: "XS",
    Name: "Kids",
    Description: "Beauty",
    PUBLISHED: false,
    ACTIONS: "Search",
  },
  {
    ID: "93-800-7305",
    Icon: "3XL",
    Name: "Baby",
    Description: "Tools",
    PUBLISHED: false,
    ACTIONS: "Edit",
  },
  {
    ID: "25-152-4230",
    Icon: "3XL",
    Name: "Electronics",
    Description: "Tools",
    PUBLISHED: false,
    ACTIONS: "Delete",
  },
  {
    ID: "92-276-8866",
    Icon: "XS",
    Name: "Outdoors",
    Description: "Music",
    PUBLISHED: true,
    ACTIONS: "Edit",
  },
  {
    ID: "08-724-8367",
    Icon: "XS",
    Name: "Clothing",
    Description: "Health",
    PUBLISHED: false,
    ACTIONS: "Edit",
  },
  {
    ID: "71-408-6112",
    Icon: "S",
    Name: "Shoes",
    Description: "Shoes",
    PUBLISHED: false,
    ACTIONS: "Edit",
  },
  {
    ID: "59-222-1901",
    Icon: "XL",
    Name: "Clothing",
    Description: "Books",
    PUBLISHED: true,
    ACTIONS: "Search",
  },
  {
    ID: "26-563-6953",
    Icon: "M",
    Name: "Games",
    Description: "Movies",
    PUBLISHED: false,
    ACTIONS: "Delete",
  },
  {
    ID: "01-479-4250",
    Icon: "2XL",
    Name: "Jewelry",
    Description: "Books",
    PUBLISHED: false,
    ACTIONS: "Edit",
  },
  {
    ID: "23-826-7250",
    Icon: "XL",
    Name: "Shoes",
    Description: "Books",
    PUBLISHED: true,
    ACTIONS: "Search",
  },
  {
    ID: "77-645-0022",
    Icon: "XL",
    Name: "Industrial",
    Description: "Electronics",
    PUBLISHED: false,
    ACTIONS: "Edit",
  },
  {
    ID: "01-591-9555",
    Icon: "XS",
    Name: "Music",
    Description: "Outdoors",
    PUBLISHED: true,
    ACTIONS: "Delete",
  },
  {
    ID: "84-848-7408",
    Icon: "2XL",
    Name: "Baby",
    Description: "Health",
    PUBLISHED: true,
    ACTIONS: "Search",
  },
  {
    ID: "77-652-6299",
    Icon: "S",
    Name: "Tools",
    Description: "Home",
    PUBLISHED: false,
    ACTIONS: "Delete",
  },
  {
    ID: "02-406-8113",
    Icon: "XL",
    Name: "Tools",
    Description: "Beauty",
    PUBLISHED: true,
    ACTIONS: "Delete",
  },
  {
    ID: "01-887-2453",
    Icon: "3XL",
    Name: "Shoes",
    Description: "Kids",
    PUBLISHED: false,
    ACTIONS: "Search",
  },
  {
    ID: "80-568-7021",
    Icon: "3XL",
    Name: "Sports",
    Description: "Sports",
    PUBLISHED: true,
    ACTIONS: "Search",
  },
  {
    ID: "93-644-6225",
    Icon: "M",
    Name: "Jewelry",
    Description: "Computers",
    PUBLISHED: false,
    ACTIONS: "Edit",
  },
  {
    ID: "60-578-5357",
    Icon: "XL",
    Name: "Jewelry",
    Description: "Clothing",
    PUBLISHED: true,
    ACTIONS: "Edit",
  },
  {
    ID: "67-214-6940",
    Icon: "XS",
    Name: "Beauty",
    Description: "Books",
    PUBLISHED: true,
    ACTIONS: "Delete",
  },
  {
    ID: "46-125-3254",
    Icon: "S",
    Name: "Toys",
    Description: "Automotive",
    PUBLISHED: false,
    ACTIONS: "Edit",
  },
  {
    ID: "17-898-7146",
    Icon: "XS",
    Name: "Outdoors",
    Description: "Music",
    PUBLISHED: false,
    ACTIONS: "Search",
  },
  {
    ID: "96-439-4708",
    Icon: "S",
    Name: "Outdoors",
    Description: "Home",
    PUBLISHED: true,
    ACTIONS: "Edit",
  },
  {
    ID: "06-492-3646",
    Icon: "M",
    Name: "Music",
    Description: "Music",
    PUBLISHED: true,
    ACTIONS: "Delete",
  },
  {
    ID: "50-268-2334",
    Icon: "L",
    Name: "Beauty",
    Description: "Tools",
    PUBLISHED: false,
    ACTIONS: "Edit",
  },
  {
    ID: "33-311-3056",
    Icon: "3XL",
    Name: "Garden",
    Description: "Sports",
    PUBLISHED: true,
    ACTIONS: "Delete",
  },
  {
    ID: "20-741-9925",
    Icon: "2XL",
    Name: "Toys",
    Description: "Books",
    PUBLISHED: false,
    ACTIONS: "Edit",
  },
  {
    ID: "62-584-5620",
    Icon: "XS",
    Name: "Automotive",
    Description: "Shoes",
    PUBLISHED: false,
    ACTIONS: "Search",
  },
  {
    ID: "01-808-2251",
    Icon: "3XL",
    Name: "Beauty",
    Description: "Books",
    PUBLISHED: true,
    ACTIONS: "Search",
  },
  {
    ID: "21-597-1013",
    Icon: "S",
    Name: "Books",
    Description: "Grocery",
    PUBLISHED: false,
    ACTIONS: "Search",
  },
  {
    ID: "72-555-8439",
    Icon: "XS",
    Name: "Books",
    Description: "Garden",
    PUBLISHED: false,
    ACTIONS: "Search",
  },
  {
    ID: "84-843-9496",
    Icon: "L",
    Name: "Garden",
    Description: "Industrial",
    PUBLISHED: false,
    ACTIONS: "Edit",
  },
  {
    ID: "82-347-7200",
    Icon: "2XL",
    Name: "Industrial",
    Description: "Clothing",
    PUBLISHED: false,
    ACTIONS: "Delete",
  },
  {
    ID: "77-436-0311",
    Icon: "L",
    Name: "Beauty",
    Description: "Baby",
    PUBLISHED: false,
    ACTIONS: "Delete",
  },
  {
    ID: "05-860-6502",
    Icon: "3XL",
    Name: "Home",
    Description: "Shoes",
    PUBLISHED: false,
    ACTIONS: "Search",
  },
  {
    ID: "65-489-3064",
    Icon: "3XL",
    Name: "Beauty",
    Description: "Kids",
    PUBLISHED: false,
    ACTIONS: "Search",
  },
  {
    ID: "28-990-4650",
    Icon: "S",
    Name: "Electronics",
    Description: "Baby",
    PUBLISHED: true,
    ACTIONS: "Search",
  },
  {
    ID: "09-719-6482",
    Icon: "2XL",
    Name: "Automotive",
    Description: "Outdoors",
    PUBLISHED: false,
    ACTIONS: "Edit",
  },
  {
    ID: "76-385-8121",
    Icon: "2XL",
    Name: "Clothing",
    Description: "Music",
    PUBLISHED: false,
    ACTIONS: "Delete",
  },
  {
    ID: "77-525-5138",
    Icon: "XL",
    Name: "Baby",
    Description: "Sports",
    PUBLISHED: true,
    ACTIONS: "Edit",
  },
  {
    ID: "27-668-8741",
    Icon: "XS",
    Name: "Games",
    Description: "Toys",
    PUBLISHED: false,
    ACTIONS: "Search",
  },
  {
    ID: "79-523-4344",
    Icon: "L",
    Name: "Industrial",
    Description: "Industrial",
    PUBLISHED: false,
    ACTIONS: "Search",
  },
  {
    ID: "89-320-5126",
    Icon: "XL",
    Name: "Industrial",
    Description: "Kids",
    PUBLISHED: false,
    ACTIONS: "Delete",
  },
  {
    ID: "37-000-7591",
    Icon: "XS",
    Name: "Health",
    Description: "Jewelry",
    PUBLISHED: true,
    ACTIONS: "Edit",
  },
  {
    ID: "02-057-1386",
    Icon: "S",
    Name: "Books",
    Description: "Health",
    PUBLISHED: true,
    ACTIONS: "Search",
  },
  {
    ID: "55-283-6943",
    Icon: "XS",
    Name: "Music",
    Description: "Garden",
    PUBLISHED: false,
    ACTIONS: "Edit",
  },
  {
    ID: "31-823-0900",
    Icon: "XL",
    Name: "Grocery",
    Description: "Automotive",
    PUBLISHED: true,
    ACTIONS: "Delete",
  },
  {
    ID: "95-872-4016",
    Icon: "2XL",
    Name: "Games",
    Description: "Electronics",
    PUBLISHED: true,
    ACTIONS: "Edit",
  },
  {
    ID: "38-239-3087",
    Icon: "XL",
    Name: "Books",
    Description: "Tools",
    PUBLISHED: true,
    ACTIONS: "Edit",
  },
  {
    ID: "45-849-8573",
    Icon: "XL",
    Name: "Industrial",
    Description: "Books",
    PUBLISHED: false,
    ACTIONS: "Edit",
  },
  {
    ID: "60-358-7774",
    Icon: "XL",
    Name: "Garden",
    Description: "Baby",
    PUBLISHED: true,
    ACTIONS: "Edit",
  },
  {
    ID: "06-737-0573",
    Icon: "XS",
    Name: "Music",
    Description: "Computers",
    PUBLISHED: false,
    ACTIONS: "Edit",
  },
  {
    ID: "99-049-4981",
    Icon: "XL",
    Name: "Home",
    Description: "Tools",
    PUBLISHED: true,
    ACTIONS: "Edit",
  },
  {
    ID: "91-442-0149",
    Icon: "L",
    Name: "Toys",
    Description: "Outdoors",
    PUBLISHED: false,
    ACTIONS: "Edit",
  },
  {
    ID: "57-578-9512",
    Icon: "S",
    Name: "Jewelry",
    Description: "Garden",
    PUBLISHED: true,
    ACTIONS: "Edit",
  },
];

export { categories };
