FROM node:alpine

RUN mkdir -p /home/app/client
# set default dir so that next commands executes in /home/app dir
WORKDIR /home/app/client

COPY package.json ./
COPY package-lock.json ./


# will execute npm install in /home/app because of WORKDIR
RUN npm install -g pnpm
RUN pnpm install

COPY ./ ./
RUN pnpm build 
EXPOSE 3000
# no need for /home/app/server.js because of WORKDIR
CMD ["pnpm","dev"]
