import localFont from "next/font/local";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import "@/app/styles/globals.css";
import React from "react";
import SessionProvider from "./sessionProvider";
import AppThemeProvider from "@/app/theme/appTheme";
import InitColorSchemeScript from "@mui/material/InitColorSchemeScript";
import dynamic from "next/dynamic";
import CartThemeProvider from "@/app/context/cartProvider";
import DraftOrderProvider from "./context/draftOrderProvider";
import RouterRefreshProvider from "@/app//context/routerRefresh";
//import AppThemeProvider to avoid ReferenceError: localStorage is not defined
const DynamicAppThemeProvider = dynamic(() => import("@/app/theme/appTheme"), {
  ssr: "",
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppRouterCacheProvider>
          <DynamicAppThemeProvider>
            <InitColorSchemeScript attribute="class" />
            <CartThemeProvider>
              <RouterRefreshProvider>
                <DraftOrderProvider>
                  <main>{children}</main>
                </DraftOrderProvider>
              </RouterRefreshProvider>
            </CartThemeProvider>
          </DynamicAppThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
